### PR TITLE
#52 limit garbage collection to the namespace scope

### PR DESCRIPTION
**Pull request by muxmuse**
This addresses https://github.com/kubecfg/kubecfg/issues/52

Adds a new cli flag `--gc-all-namespaces` to `kubecfg update`. 
- When set to false: apply the namespace scope (i.e. default namespace, adjustable with `--namespace`) to garbage collection
- When set to true (default): keep behavior unchanged

### CODE REVIEW

**Comment by primeroz** [comment]
LGTM but would be great to add this new flag to the integration test https://github.com/kubecfg/kubecfg/blob/main/integration/update_test.go#L453

**Review by primeroz — APPROVED** [review]
LGTM , @mkmik please review as well ?

**Review by mkmik — APPROVED** [review]
LGTM;

failing test

and TIL GH now can show the failure inline:

image


yay

**Comment by muxmuse** [comment]
Sorry for the trivial error. Is there a preferred way to run integration tests locally before committing? I could build scripts based on github actions, but there may be a different way?

**Comment by primeroz** [comment]
You should be able to run the ingration tests using the same command defined in the .github workflow

**Comment by muxmuse** [comment]
Tests should pass now. Please let me know if a fresh PR is preferred for a cleaner history (see: https://github.com/muxmuse/kubecfg/pull/4/files). Thank you

**Comment by mkmik** [comment]
@muxmuse Thanks!

**Pull request merged**
