### PR TITLE
Add a basic Dockerfile

### PR DESCRIPTION
**Pull request by muxmuse**
This PR adds a Dockerfile for an alpine based image with the kubecfg executable.

### CODE REVIEW

**Comment by mkmik** [comment]
Thanks.

I'd prefer to use https://github.com/ko-build/ko

The main selling points are: no dependency on docker required ro build and multi-arch container cross compilation for free

**Comment by mkmik** [comment]
> Example: https://github.com/mkmik/generated-secrets/blob/e2454fa6a86e97be5f01e1073cad8254e3148b07/.github/workflows/image-gh.yml#L21

actually a better example is https://github.com/mkmik/pigox/blob/main/.github/workflows/go.yml

**Comment by muxmuse** [comment]
Thank you! I'll check it out and adjust this PR.

**Comment by muxmuse** [comment]
Dockerfile has been replaced by a github workflow step that runs `ko build` after "Upload kubecfg artifact". This is a small increment as the image is only tagged with the commit hash and not with a version. It might still be helpful as an official source of kubecfg images.

**Review by mkmik — APPROVED** [review]

**Comment by mkmik** [comment]
will fix CI permissions

**Comment by mkmik** [comment]
ok, the images are available:

```bash
docker pull ghcr.io/kubecfg/kubecfg/kubecfg:latest
```

I'll figure out release tagging at next release

**Pull request merged**
